MusicApp/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:create, :new, :show]
  resource :session, only: [:create, :new, :destroy]

  resources :bands do
    resources :albums, only: [:new, :index]
  end

  resources :albums, only: [:create, :edit, :show, :update, :destroy, :index] do
    resources :tracks, only: [:new]
  end

  resources :tracks, except: [:new, :index]
end

MusicApp/app/models/album.rb
# == Schema Information
#
# Table name: albums
#
#  id         :integer          not null, primary key
#  band_id    :integer          not null
#  title      :string           not null
#  year       :string           not null
#  live       :boolean          default(FALSE), not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Album < ApplicationRecord
  validates :band_id, :title, :year, presence: true
  validates :title, uniqueness: { scope: :band_id }

  has_many :tracks
  belongs_to :band
end

MusicApp/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

MusicApp/app/models/band.rb
# == Schema Information
#
# Table name: bands
#
#  id         :integer          not null, primary key
#  name       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Band < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_many :albums
end

MusicApp/app/models/track.rb
# == Schema Information
#
# Table name: tracks
#
#  id         :integer          not null, primary key
#  album_id   :integer          not null
#  title      :string           not null
#  ord        :string           not null
#  lyrics     :text
#  bonus      :boolean          default(FALSE), not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Track < ApplicationRecord
  validates :album_id, :title, :ord, presence: true
  validates :title, uniqueness: { scope: :album_id }

  belongs_to :album
end

MusicApp/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  email           :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ApplicationRecord

  validates :email, :password_digest, :session_token, presence: true
  validates :password, length: { minimum: 6, allow_nil: true }
  validates :email, uniqueness: true

  after_initialize :ensure_session_token

  attr_reader :password

  def self.generate_session_token
    self.session_token = SecureRandom::urlsafe_base64
  end

  def self.find_by_credentials(email, pw)
    user = User.find_by(email: email)
    return nil unless user
    user.is_password?(pw) ? user : nil
  end

  def password=(pw)
    @password = pw
    self.password_digest = BCrypt::Password.create(pw)
  end

  def is_password?(pw)
    BCrypt::Password.new(self.password_digest).is_password?(pw)
  end

  def ensure_session_token
    self.session_token ||= SecureRandom::urlsafe_base64
  end

  def reset_session_token!
    self.session_token = SecureRandom::urlsafe_base64
    self.save!
    self.session_token
  end
end

MusicApp/app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  def index
    @albums = Album.all
    render :index
  end

  def edit
    @album = Album.find_by(id: params[:id])
    render :edit
  end

  def new
    @album = Album.new(band_id: params[:band_id])
    @band = Band.find_by(id: params[:band_id])
  end

  def create
    @album = Album.new(album_params)
    if @album.save
      redirect_to album_url(@album)
    else
      flash.now[:errors] = @album.errors.full_messages
    end
  end

  def show
    @album = Album.find_by(id: params[:id])
    render :show
  end

  def update
    @album = Album.find_by(id: params[:id])
    if @album.update_attributes(album_params)
      redirect_to album_url(@album)
    else
      flash.now[:errors] = @album.errors.full_messages
      render :edit
    end
  end

  def destroy
    @album = Album.find_by(id: params[:id])
    @album.destroy
    redirect_to band_url(@album.band_id)
  end

  private

  def album_params
    params.require(:album).permit(:title, :year)
  end

end

MusicApp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def login(user)
    @current_user = user
    session[:session_token] = user.reset_session_token!
  end

  def logged_in?
    !!current_user
  end

  def logout
    current_user.reset_session_token! unless current_user.nil?
    session[:session_token] = nil
  end

  # def require_user!
  # end

end

MusicApp/app/controllers/bands_controller.rb
class BandsController < ApplicationController
end

MusicApp/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.find_by_credentials(params[:users][:email], params[:users][:password])
    if @user
      login(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = ["Invalid username or password"]
      render :new
    end
  end

  def destroy
    logout
    redirect_to new_session_url
  end

end

MusicApp/app/controllers/tracks_controller.rb
class TracksController < ApplicationController
end

MusicApp/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def show
    render :show
  end

  def user_params
    params.require(:users).permit(:email, :password)
  end
end

MusicApp/app/helpers/albums_helper.rb
module AlbumsHelper
end

MusicApp/app/helpers/application_helper.rb
module ApplicationHelper
  def auth_token
    "<input
          type=\"hidden\"
          name=\"authenticity_token\"
          value=\"#{form_authenticity_token}\">".html_safe
  end
end

MusicApp/app/helpers/bands_helper.rb
module BandsHelper
end

MusicApp/app/helpers/sessions_helper.rb
module SessionsHelper
end

MusicApp/app/helpers/tracks_helper.rb
module TracksHelper
end

MusicApp/app/helpers/users_helper.rb
module UsersHelper
end

MusicApp/app/views/albums/edit.html.erb
<h1>Edit an album!<h1>

<form action="<%= album_url %>" method="post">
  <%= auth_token %>
  <input type="hidden" name="_method" value="PATCH">

  <label for="album-band">Band Name:</label>
  <select id="album-band" name="album[band_id]">
    <% Band.all.each do |band| %>
      <option
      <%= "selected" if @album.band_id == band.id%>
        value="<% band.id %>">
        <%= band.name %>
      </option>
      <% end %>
  </select>
  <br>
  <br>
  <label for="title">Title</label>
  <input id="title" type="text" name="album[title]" value="<%= @album.title %>">
  <br>
  <br>
  <label for="year">Year Released</label>
  <input type="text" name="album[year]" value=" <%= @album.year %>">
  <input type="submit" value="Update!">
</form>

MusicApp/app/views/albums/show.html.erb
<h3><%= @album.band.name %></h3> <br>
<h3><%= @album.title %></h3> <br>
<h3><%= @album.year %></h3> <br>
<h3><%= @album.live ? "Live Track!" : "Studio Track" %></h3>

MusicApp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <% if logged_in? %>
    <%= current_user.email %>
    <%= button_to "logout", session_url, method: :delete %>
    <% else %>
    <%= link_to "login", new_session_url %>
    <%= link_to "sign up", new_user_url %>
    <% end %>
    <%= yield %>
  </body>
</html>

MusicApp/app/views/users/new.html.erb
<form action="<%= users_url  %>" method="post">
  <%= auth_token %>

  <label for="email">Enter your email:</label>
  <input type="text"
  name="users[email]"
  value="<%= @user.email %>">
  <br>
  <br>

  <label for="password">Enter your password</label>
  <input type="password" name="users[password]">
  <br>
  <br>

  <input type="submit" value="Sign Up!">
</form>

MusicApp/app/views/users/show.html.erb
<%= "Hi #{current_user.email}" %>